name: Test

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [8.0, 7.4 ]
                laravel: [ 8.* ,7.*, 6.*]
                dependency-version: [ prefer-stable ]
                include:
                    - laravel: 8.*
                      testbench: 6.*
                    - laravel: 7.*
                      testbench: 5.*
                    - laravel: 6.*
                      testbench: 4.*

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: curl, mbstring, zip, pcntl, sqlite, pdo_sqlite, iconv
                coverage: none

            - name: Install dependencies - L${{ matrix.laravel }}
              if: ${{ matrix.laravel }} == '8.*'
              run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer require --dev "jiannei/laravel-enum" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            -  name: Install dependencies - L${{ matrix.laravel }}
               if: ${{ matrix.laravel }} == '7.*' || ${{ matrix.laravel }} == '6.*'
               run: |
                   composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "symfony/console:>=4.3.4" "mockery/mockery:^1.3.2" --no-interaction --no-update
                   composer require --dev "jiannei/laravel-enum" --no-interaction --no-update
                   composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit